options:
  formatter: stylish
  merge-default-rules: false
files:
  include: 'src/blocks/**/*.s+(a|c)ss'
rules:
  #Documantation: https://github.com/sasstools/sass-lint/tree/develop/docs/rules
  bem-depth:
    - 1
    - max-depth: '1'

  class-name-format:
    - 1
    - convention: strictbem

  border-zero:
    - 1
    - convention: '0'

  nesting-depth:
    - 1
    - max-depth: 2

  no-css-comments: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 1
  no-ids: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-universal-selectors: 1
  one-declaration-per-line: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-bang:
    - 1
    - include: true

  space-before-brace:
    - 1
    - include: true

  space-before-colon:
    - 1
    - include: false

  space-between-parens:
    - 1
    - include: false

  trailing-semicolon:
    - 1
    - include: true

  url-quotes: 1

  variable-name-format:
    - 1
    - convention: strictbem

  zero-unit:
    - 0
    - include: false
